name: Deploy to Bluehost

on:
  push:
    branches:
      - main  # Or 'master' if your branch is named that
  workflow_dispatch: #<--adds the manual trigger button
  
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v4

    - name: ðŸ• Update version file
      run: |
        echo $(date -u +"%Y%m%d%H%M%S") > motionmapmaker/version.txt
        cat motionmapmaker/version.txt

    - name: ðŸ“‚ Sync files- name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
      
          # strongly recommended: be explicit about protocol/port
          protocol: ftp          # or: ftps, ftps-legacy
          port: 21               # 21 for ftp/explicit ftps; 990 for ftps-legacy
      
          local-dir: ./public/   # must end with /
          server-dir: ./         # must end with /
      
          timeout: 180000        # 180s; raise to 600000 if needed
          log-level: verbose
